packages = ["i3-wm", "i3lock", "i3status", "dmenu", "arandr"]
shared_directories = ["i3_config"]
script = """
mkdir -p /home/${ALMA_USER}/.config/i3/
cp /shared_dirs/i3_config/i3_config /home/${ALMA_USER}/.config/i3/config
chown ${ALMA_USER} /home/${ALMA_USER}/.config/i3/config
chown -R ${ALMA_USER} /home/${ALMA_USER}/.config/i3
chgrp -R ${ALMA_USER} /home/${ALMA_USER}/.config/i3
mkdir -p /home/${ALMA_USER}/.config/i3status/
cp /shared_dirs/i3_config/i3status_config /home/${ALMA_USER}/.config/i3status/config
chown ${ALMA_USER} /home/${ALMA_USER}/.config/i3status/config
chown -R ${ALMA_USER} /home/${ALMA_USER}/.config/i3status
chgrp -R ${ALMA_USER} /home/${ALMA_USER}/.config/i3status
"""
environment_variables = ["ALMA_USER"]
